
spring:
  datasource:
    # H2 ë©”ëª¨ë¦¬ ì‚¬ìš©
    url: jdbc:h2:mem:step1189;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # ì›¹ ì½˜ì†” ì‚¬ìš©í•  ìˆ˜ ìˆê²Œ í•¨
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create # í˜¹ì€ update
    show-sql: true # ì½˜ì†”ì—ì„œ ë‚ ì•„ê°€ëŠ” SQL ì¿¼ë¦¬ë¬¸ì„ ë³´ì—¬ì¤Œ
    properties:
      hibernate:
        format_sql: true # SQLì„ ë³´ê¸°ì¢‹ê²Œ ì •ë ¬í•´ì„œ ë³´ì—¬ì¤Œ
    defer-datasource-initialization: true # Hibernate ì´ˆê¸°í™” í›„ data.sql ì‹¤í–‰

  sql:
    init:
      mode: always # í•­ìƒ ì‹¤í–‰

  security:
    oauth2:
      client:
        registration:
          google:
            # ğŸ’¡ êµ¬ê¸€ í´ë¼ìš°ë“œ ì½˜ì†”ì—ì„œ ë°œê¸‰ë°›ì€ ì •ë³´ë¥¼ ì—¬ê¸° ë„£ì–´ì•¼ í•´!
            client-id:
            client-secret:
            scope:
              - email
              - profile